const {createClient}=supabase;const db=createClient(STORE_CONFIG.SUPABASE_URL,STORE_CONFIG.SUPABASE_KEY);let cats=[],editing=null,productsCache=[],imageInputs=[];
async function login(e){e.preventDefault();let {error}=await db.auth.signInWithPassword({email:email.value,password:password.value});if(error){loginMsg.textContent="بيانات الدخول غير صحيحة أو الحساب غير مفعّل.";return}await init()}
async function init(){let {data:{user}}=await db.auth.getUser();if(!user){loginBox.style.display="block";dashboard.style.display="none";return}let {data:a}=await db.from("admins").select("id,is_admin").eq("id",user.id).maybeSingle();if(!a?.is_admin){await db.auth.signOut();loginMsg.textContent="هذا الحساب ليس مديرًا.";return}loginBox.style.display="none";dashboard.style.display="block";let c=await db.from("categories").select("*").order("name");cats=c.data||[];pcat.innerHTML=cats.map(x=>`<option value="${x.id}">${x.icon} ${x.name}</option>`).join("");loadProducts();loadOrders()}
async function loadProducts(){let {data}=await db.from("products").select("*,categories(name),product_images(id,image_url,sort_order)").order("created_at",{ascending:false});productsCache=data||[];adminProducts.innerHTML=productsCache.map(p=>{let imgs=(p.product_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));let cover=p.image_url||imgs[0]?.image_url||"";return `<article class="card"><div class="noimg">${cover?`<img src="${safe(cover)}" style="width:100%;height:100%;object-fit:cover">`:"🛍️"}</div><div class="cardbody"><small>${safe(p.categories?.name||"")}</small><h3>${safe(p.name)}</h3><small>${imgs.length?`📷 ${imgs.length} صور إضافية`:""}</small><div class="price">${Number(p.price).toLocaleString("ar-DZ")} دج</div><div class="row"><button class="main-btn" onclick="editProductById(${p.id})">تعديل</button><button class="danger" onclick="del(${p.id})">حذف</button></div></div></article>`}).join("")}
function editProductById(id){let p=productsCache.find(x=>Number(x.id)===Number(id));if(p)editProduct(p)}
function resetImagePickers(){imageInputs=[];imagePickers.innerHTML="";imagePreview.innerHTML="";addImagePicker()}
function addImagePicker(){let input=document.createElement("input");input.type="file";input.accept="image/*";input.multiple=true;input.style="display:block;width:100%;margin:6px 0";input.addEventListener("change",()=>renderImagePreview());imagePickers.appendChild(input);imageInputs.push(input)}
function renderImagePreview(){let files=[];for(const input of imageInputs)files.push(...(input.files||[]));imagePreview.innerHTML=files.map(f=>`<div style="width:82px;text-align:center"><img src="${URL.createObjectURL(f)}" style="width:76px;height:76px;object-fit:cover;border-radius:10px"><small style="display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${safe(f.name)}</small></div>`).join("")}
function showAdd(){editing=null;formTitle.textContent="إضافة منتج";document.getElementById("productForm").reset();oldimage.value="";resetImagePickers();productModal.style.display="block"}
function editProduct(p){editing=p;pname.value=p.name;pprice.value=p.price;pcat.value=p.category_id;pdesc.value=p.description||"";oldimage.value=p.image_url||"";formTitle.textContent="تعديل المنتج";resetImagePickers();productModal.style.display="block"}
function closeP(){productModal.style.display="none"}
async function saveProduct(e){e.preventDefault();let image=oldimage.value||"";let files=[];for(const input of imageInputs)files.push(...(input.files||[]));let uploaded=[];if(files.length){for(let f of files){let ext=(f.name.split(".").pop()||"jpg").toLowerCase();let path=`${crypto.randomUUID()}.${ext}`;let up=await db.storage.from("product-images").upload(path,f,{upsert:false});if(up.error)return alert("تعذر رفع إحدى الصور. تحقق من Storage والصلاحيات.");let url=db.storage.from("product-images").getPublicUrl(path).data.publicUrl;uploaded.push(url);if(!image)image=url}}
let row={name:pname.value,price:Number(pprice.value),category_id:Number(pcat.value),description:pdesc.value,image_url:image,active:true};let r=editing?await db.from("products").update(row).eq("id",editing.id):await db.from("products").insert(row).select().single();if(r.error)return alert("تعذر حفظ المنتج.");let productId=editing?editing.id:r.data.id;
if(uploaded.length){let base=(editing?.product_images||[]).length;let rows=uploaded.map((url,i)=>({product_id:productId,image_url:url,sort_order:base+i}));let ir=await db.from("product_images").insert(rows);if(ir.error)return alert("تم حفظ المنتج لكن تعذر حفظ الصور الإضافية.")}
closeP();loadProducts()}
async function del(id){if(!confirm("حذف المنتج؟"))return;await db.from("products").delete().eq("id",id);loadProducts()}
async function loadOrders(){let {data}=await db.from("orders").select("*").order("created_at",{ascending:false});orders.innerHTML=(data||[]).map(o=>`<div class="order"><div class="row"><b>طلب #${o.id}</b><span>${new Date(o.created_at).toLocaleString("ar-DZ")}</span></div><p>👤 ${safe(o.customer_name)} — 📱 ${safe(o.phone)} — 📍 ${safe(o.wilaya)}</p><p>العنوان: ${safe(o.address)} | ${safe(o.delivery_method)} | ${Number(o.total).toLocaleString("ar-DZ")} دج</p><select class="status" onchange="status(${o.id},this.value)">${["جديد","تم التأكيد","قيد الشحن","تم التسليم","ملغى"].map(s=>`<option ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></div>`).join("")}
async function status(id,v){await db.from("orders").update({status:v}).eq("id",id);loadOrders()}function tab(id){productsTab.style.display=id==="productsTab"?"block":"none";ordersTab.style.display=id==="ordersTab"?"block":"none"}async function logout(){await db.auth.signOut();location.reload()}function safe(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}init();
