const {createClient}=supabase;
const db=createClient(STORE_CONFIG.SUPABASE_URL,STORE_CONFIG.SUPABASE_KEY);
let products=[],categories=[],cart=[],active=null;
const $=id=>document.getElementById(id);
const wilayas=["أدرار","الشلف","الأغواط","أم البواقي","باتنة","بجاية","بسكرة","بشار","البليدة","البويرة","تمنراست","تبسة","تلمسان","تيارت","تيزي وزو","الجزائر","الجلفة","جيجل","سطيف","سعيدة","سكيكدة","سيدي بلعباس","عنابة","قالمة","قسنطينة","المدية","مستغانم","المسيلة","معسكر","ورقلة","وهران","البيض","إليزي","برج بوعريريج","بومرداس","الطارف","تندوف","تيسمسيلت","الوادي","خنشلة","سوق أهراس","تيبازة","ميلة","عين الدفلى","النعامة","عين تموشنت","غرداية","غليزان","تميمون","برج باجي مختار","أولاد جلال","بني عباس","عين صالح","عين قزام","تقرت","جانت","المغير","المنيعة"];
const deliveryPrices={"أدرار":[1000,500],"الشلف":[600,350],"الأغواط":[800,350],"أم البواقي":[600,350],"باتنة":[600,350],"بجاية":[600,350],"بسكرة":[800,350],"بشار":[900,500],"البليدة":[450,450],"البويرة":[550,350],"تمنراست":[1200,700],"تبسة":[650,350],"تلمسان":[600,350],"تيارت":[600,350],"تيزي وزو":[550,350],"الجزائر":[300,300],"الجلفة":[800,450],"جيجل":[600,350],"سطيف":[600,350],"سعيدة":[650,350],"سكيكدة":[600,350],"سيدي بلعباس":[600,350],"عنابة":[600,350],"قالمة":[650,350],"قسنطينة":[600,350],"المدية":[550,350],"مستغانم":[650,350],"المسيلة":[650,350],"معسكر":[600,350],"ورقلة":[800,450],"وهران":[600,350],"البيض":[900,500],"إليزي":[1200,900],"برج بوعريريج":[600,350],"بومرداس":[450,300],"الطارف":[650,350],"تندوف":[1100,700],"تيسمسيلت":[600,350],"الوادي":[800,450],"خنشلة":[650,350],"سوق أهراس":[650,400],"تيبازة":[450,350],"ميلة":[650,350],"عين الدفلى":[550,350],"النعامة":[800,450],"عين تموشنت":[600,400],"غرداية":[800,450],"غليزان":[600,400],"تميمون":[1100,700],"برج باجي مختار":[99999,99999],"أولاد جلال":[800,500],"بني عباس":[1000,1000],"عين صالح":[1200,900],"عين قزام":[99999,99999],"تقرت":[800,450],"جانت":[99999,99999],"المغير":[850,850],"المنيعة":[850,500]};
function safe(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function deliveryPrice(){const d=deliveryPrices[$("wilaya").value];return !d?0:$('delivery').value==='home'?d[0]:$('delivery').value==='office'?d[1]:0}
function updateTotal(){const subtotal=cart.reduce((s,p)=>s+Number(p.price),0);$("total").textContent=(subtotal+deliveryPrice()).toLocaleString("ar-DZ")+" دج"}
function updateDelivery(){const w=$("wilaya").value,d=deliveryPrices[w],sel=$("delivery");sel.innerHTML='<option value="">طريقة الاستلام</option>';if(!d){updateTotal();return}sel.innerHTML+=`<option value="home">التوصيل إلى المنزل — ${d[0].toLocaleString("ar-DZ")} دج</option><option value="office">التوصيل إلى المكتب — ${d[1].toLocaleString("ar-DZ")} دج</option>`;updateTotal()}
async function load(){
  $("wilaya").innerHTML='<option value="">اختر الولاية</option>'+wilayas.map(x=>`<option>${x}</option>`).join("");
  $("wilaya").addEventListener("change",updateDelivery);$("delivery").addEventListener("change",updateTotal);
  let c=await db.from("categories").select("*").order("name");categories=c.data||[];
  let p=await db.from("products").select("*,categories(name,icon),product_images(id,image_url,sort_order)").eq("active",true).order("created_at",{ascending:false});products=p.data||[];render();
}
function render(){const q=($("search").value||"").toLowerCase();$("cats").innerHTML=categories.map(c=>`<div class="cat ${active===c.id?'active':''}" onclick="filterCat(${c.id})"><i>${c.icon||'📦'}</i>${safe(c.name)}</div>`).join("");const arr=products.filter(p=>(!active||p.category_id===active)&&(!q||String(p.name).toLowerCase().includes(q)));$("grid").innerHTML=arr.length?arr.map(p=>{let imgs=(p.product_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(x=>x.image_url);if(p.image_url&&!imgs.includes(p.image_url))imgs.unshift(p.image_url);const cover=imgs[0]||"";return `<article class="card">${cover?`<img src="${safe(cover)}" onclick="openGallery(${p.id})" style="cursor:pointer">`:`<div class="noimg">🛍️</div>`}<div class="cardbody"><small>${safe(p.categories?.name||"")}</small><h3>${safe(p.name)}</h3><p>${safe(p.description||"")}</p>${imgs.length>1?`<button class="main-btn" style="width:100%;margin-bottom:8px" onclick="openGallery(${p.id})">📷 عرض ${imgs.length} صور</button>`:""}<div class="price">${Number(p.price).toLocaleString("ar-DZ")} دج</div><button class="add" onclick="add(${p.id})">أضف إلى السلة</button></div></article>`}).join(""):"<p>لا توجد منتجات في هذا القسم حاليًا.</p>"}
function filterCat(id){active=active===id?null:id;render();$("products").scrollIntoView({behavior:"smooth"})}
function openGallery(id){const p=products.find(x=>x.id===id);if(!p)return;let imgs=(p.product_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(x=>x.image_url);if(p.image_url&&!imgs.includes(p.image_url))imgs.unshift(p.image_url);if(!imgs.length)return;$("galleryMain").src=imgs[0];$("galleryThumbs").innerHTML=imgs.map(u=>`<img src="${safe(u)}" onclick="$('galleryMain').src=this.src" style="width:70px;height:70px;object-fit:cover;border-radius:10px;cursor:pointer">`).join("");$("galleryModal").style.display="block"}
function closeGallery(){$("galleryModal").style.display="none"}
function add(id){const p=products.find(x=>x.id===id);if(p)cart.push(p);drawCart();alert("تمت إضافة المنتج للسلة ✅")}
function drawCart(){$("count").textContent=cart.length;$("items").innerHTML=cart.length?cart.map((p,i)=>`<div class="cartrow"><div class="row"><span>${safe(p.name)}</span><b>${Number(p.price).toLocaleString("ar-DZ")} دج</b><button class="danger" onclick="cart.splice(${i},1);drawCart()">حذف</button></div></div>`).join(""):"السلة فارغة";updateTotal()}
function openCart(){drawCart();$("cartModal").style.display="block"}function closeM(){$("cartModal").style.display="none"}
async function order(e){e.preventDefault();if(!cart.length)return alert("السلة فارغة");const w=$("wilaya").value,mode=$("delivery").value,fee=deliveryPrice();if(!w||!mode)return alert("اختر الولاية وطريقة الاستلام.");if(fee>=99999)return alert("التوصيل غير متاح حاليًا لهذه الولاية.");const subtotal=cart.reduce((s,p)=>s+Number(p.price),0),sum=subtotal+fee,method=mode==='home'?"التوصيل إلى المنزل":"التوصيل إلى المكتب",items=cart.map(p=>({product_id:p.id,product_name:p.name,price:Number(p.price),quantity:1}));const {data:o,error}=await db.rpc("create_order",{p_customer_name:$("name").value,p_phone:$("phone").value,p_wilaya:w,p_address:$("address").value,p_delivery_method:method,p_total:sum,p_items:items});if(error){console.error(error);return alert("تعذر إرسال الطلب. تحقق من إعداد Supabase.")}const oid=o?.id||o?.order_id||"",msg=`طلب جديد #${oid}\n${cart.map(p=>`- ${p.name} | ${Number(p.price).toLocaleString("ar-DZ")} دج`).join("\n")}\nسعر المنتجات: ${subtotal.toLocaleString("ar-DZ")} دج\nالتوصيل: ${fee.toLocaleString("ar-DZ")} دج\nالمجموع: ${sum.toLocaleString("ar-DZ")} دج\nالاسم: ${$("name").value}\nالهاتف: ${$("phone").value}\nالولاية: ${w}\nالعنوان: ${$("address").value}\nالاستلام: ${method}\nالدفع: عند الاستلام`;cart=[];drawCart();location.href=`https://wa.me/${STORE_CONFIG.WHATSAPP}?text=${encodeURIComponent(msg)}`}
load();
